---
namespace: code3tech
name: devtools
version: 1.0.0
readme: README.md

authors:
  - Code3Tech DevOps Team <suporte@kode3.tech>

description: >-
  Ansible Collection for DevOps tools installation and configuration.
  Includes roles for Docker, Podman, and other development tools commonly
  used in DevOps workflows. Supports Ubuntu, Debian, and RHEL-based systems.

license:
  - MIT

tags:
  - devops
  - tools
  - docker
  - podman
  - containers
  - development
  - infrastructure
  - automation
  - ci
  - cd

dependencies:
  'community.docker': '>=3.4.0'
  'containers.podman': '>=1.10.0'

repository: https://github.com/kode3tech/ansible-col-devtools
documentation: https://github.com/kode3tech/ansible-col-devtools/blob/main/README.md
homepage: https://github.com/kode3tech/ansible-col-devtools
issues: https://github.com/kode3tech/ansible-col-devtools/issues

build_ignore:
  - .git
  - .github
  - .gitignore
  - .venv
  - .ansible
  - .python-version
  - .tool-versions
  - '*.pyc'
  - '*.pyo'
  - '*.swp'
  - '*.bak'
  - '*.tmp'
  - '*~'
  - __pycache__
  - .pytest_cache
  - .molecule
  - .cache
  - '*.log'
  - .DS_Store
  - Thumbs.db
