---
namespace: kode3tech
name: devtools
version: 1.0.0
readme: README.md

authors:
  - Kode3Tech DevOps Team <devops@kode3.com.br>

description: >-
  Ansible Collection for DevOps tools installation and configuration.
  Includes roles for Docker, Podman, and other development tools commonly
  used in DevOps workflows. Supports Ubuntu, Debian, and RHEL-based systems.

license:
  - MIT

tags:
  - devops
  - tools
  - docker
  - podman
  - containers
  - development
  - infrastructure
  - automation
  - ci
  - cd

dependencies: {}

repository: https://github.com/kode3tech/ansible-devtools
documentation: https://github.com/kode3tech/ansible-devtools/blob/main/README.md
homepage: https://github.com/kode3tech/ansible-devtools
issues: https://github.com/kode3tech/ansible-devtools/issues

build_ignore:
  - .git
  - .github
  - .gitignore
  - .venv
  - .ansible
  - .python-version
  - .tool-versions
  - '*.pyc'
  - '*.pyo'
  - '*.swp'
  - '*.bak'
  - '*.tmp'
  - '*~'
  - __pycache__
  - .pytest_cache
  - .molecule
  - .cache
  - '*.log'
  - .DS_Store
  - Thumbs.db
