---
namespace: code3tech
name: devtools
version: 1.4.0
readme: README.md

authors:
  - Code3Tech DevOps Team <suporte@kode3.tech>

description: >-
  Ansible Collection for DevOps tools installation and configuration.
  Includes roles for Azure DevOps Agents, GitHub Actions Runners, GitLab CI Runners, Docker, Podman, and asdf version manager.
  Supports Ubuntu, Debian, and RHEL-based systems with production-ready configurations.

license:
  - MIT

tags:
  - devops
  - tools
  - docker
  - podman
  - containers
  - development
  - infrastructure
  - automation
  - ci
  - cd
  - azure
  - azuredevops
  - agents
  - asdf
  - versionmanager
  - github
  - actions
  - runners
  - selfhosted

dependencies:
  'community.docker': '>=3.4.0'
  'containers.podman': '>=1.10.0'

repository: https://github.com/kode3tech/ansible-col-devtools
documentation: https://github.com/kode3tech/ansible-col-devtools/blob/main/README.md
homepage: https://github.com/kode3tech/ansible-col-devtools
issues: https://github.com/kode3tech/ansible-col-devtools/issues

build_ignore:
  - .git
  - .github
  - .gitignore
  - .venv
  - .ansible
  - '**/.ansible'
  - '**/.ansible/**'
  - .python-version
  - .tool-versions
  - collections
  - '**/collections'
  - '**/collections/**'
  - _temp
  - '_temp/**'
  - '*.pyc'
  - '*.pyo'
  - '*.swp'
  - '*.bak'
  - '*.tmp'
  - '*~'
  - __pycache__
  - '**/__pycache__'
  - '**/__pycache__/**'
  - .pytest_cache
  - '**/.pytest_cache'
  - '**/.pytest_cache/**'
  - .molecule
  - '**/.molecule'
  - '**/.molecule/**'
  - .cache
  - '**/.cache'
  - '**/.cache/**'
  - '*.log'
  - '**/*.log'
  - .DS_Store
  - '**/Thumbs.db'
