---
namespace: code3tech
name: devtools
version: 1.5.0
readme: README.md

authors:
  - Code3Tech DevOps Team <suporte@kode3.tech>

description: >-
  Production-ready Ansible Collection for automating CI/CD infrastructure deployment.
  Deploy and manage self-hosted runners and agents across multiple CI/CD providers
  (Azure DevOps, GitHub Actions, GitLab CI), container platforms (Docker, Podman),
  and development tools (asdf version manager). Unified configuration, API-driven
  lifecycle management, and multi-platform support (Ubuntu, Debian, RHEL).
  Battle-tested for enterprise production environments.

license_file: LICENSE

tags:
  - cicd
  - infrastructure
  - automation
  - containers
  - docker
  - podman
  - selfhosted
  - runners
  - agents
  - azure
  - github
  - gitlab
  - devops
  - deployment
  - orchestration
  - linux
  - production
  - api
  - lifecycle
  - versionmanager

dependencies:
  'community.docker': '>=3.4.0'
  'containers.podman': '>=1.10.0'

repository: https://github.com/kode3tech/ansible-col-devtools
documentation: https://github.com/kode3tech/ansible-col-devtools/blob/main/README.md
homepage: https://github.com/kode3tech/ansible-col-devtools
issues: https://github.com/kode3tech/ansible-col-devtools/issues

build_ignore:
  # Version control
  - .git
  - .github
  - .gitignore

  # Python environments
  - .venv
  - __pycache__
  - '**/__pycache__/**'
  - '*.pyc'
  - '*.pyo'

  # Testing & Development
  - .pytest_cache
  - '**/.pytest_cache/**'
  - .molecule
  - '**/.molecule/**'
  - collections
  - '**/collections/**'

  # Temporary files
  - _temp
  - '_temp/**'
  - .tmp
  - '*.tmp'
  - '*.swp'
  - '*.bak'
  - '*~'

  # Logs and caches
  - '*.log'
  - .cache
  - '**/.cache/**'
  - .ansible
  - '**/.ansible/**'

  # OS files
  - .DS_Store
  - '**/Thumbs.db'

  # Tool configs
  - .python-version
  - .tool-versions
